config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  #http method, "url", "controller#method", "route verb"
  get "/about", to: "pages#about", as: "about"



  resources :authors do
    resources :books
  end

  resources :books

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord

  #author has one or more instances of books related to it:
  has_many :books

end

app/models/book.rb
class Book < ApplicationRecord

  # book has one author connected to it
  belongs_to :author

  has_and_belongs_to_many :categories

  validates :title, presence: true, length: {minimum: 1}
  validates :author_id, presence: true


end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all.sort()
  end

  def new
    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.create(author_params)
    @author.save

    redirect_to root_path
  end

  def author_params
    params.require(:author).permit(:full_name, :date_of_birth)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all()
  end


  def show
    @book = Book.find(params[:id])
  end


  def new
    @book = Book.new
  end


  def create
    @book = Book.create(book_params)
    #<< metoden fortæller activeRecord at den skal oprette rows i jointable
    # Læg mærke til, vi peger where metoden på, Category id skal være lige med det vi finder i params, under :book key, dernæst :category_ids vi får fra view, returnér den værdi
    # og sammenlign.
    # og sidst, forbind bogen til de kategorier, opret i jointable.
    @book.categories << Category.where(id: params[:book][:category_ids])

    if @book.save
      redirect_to controller: "books", action: "index"
    else
      render :new, status: :bad_request
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to controller: "books", action: "index"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    render 'pages/home'
  end


  private
  def book_params
    params.require(:book).permit(:title,:description,:release_date,:rating,:author_id,:category_ids => [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end


  def new
    @category = Category.new
  end


  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to controller: "categories", action: "index"
    else
      render :new, status: :bad_request
    end
  end


  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



  #typisk navngivning for en controller som denne, der bare tilbyder views uden data
  # er main_controller, ikke pages_controller
  def home
    render 'home'
  end


  def about
    #aboutpage
    # default opførsel med en tom metode er
    # render("about")
    # dvs. den peger på et view af samme navn som metoden
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/_form.erb
<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %>
    <% @author.errors.full_messages_for(:full_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :date_of_birth %><br>
    <%= form.date_select :date_of_birth %>
    <% @author.errors.full_messages_for(:date_of_birth).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

<p><%= link_to "Tilbage til forfattere", authors_path %></p>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/authors/index.erb
<h1>Forfattere</h1>


<%= link_to "Ny forfatter" , new_author_path %>

<ul>

  <% @authors.each do |author| %>
    <li>
      <%= link_to author.full_name, author %>
    </li>
  <%end %>

</ul>

<%= link_to "tilbage til forside" ,root_path %>

app/views/authors/new.erb
<h1>Ny forfatter</h1>

<%= render "form", model: @author %>

app/views/authors/show.erb
<div>
  <strong>Forfatter</strong>
  <p><%= @author.full_name %></p>
  <%= @author.date_of_birth %>

  <br>
  <strong>Bøger skrevet:</strong>

  <ul>
    <% @author.books.each do |book| %>
      <li><%= link_to book.title, book %></li>
    <% end %>

  </ul>

</div>


<p><%= link_to "Tilbage til forfattere", authors_path %></p>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/books/_book.erb
<li>
  <strong>Titel:</strong>
  <%= book.title %>
  <br>
  Beskrivelse:
  <%= book.description %>
  <br>

  <strong>Categories:</strong>
  <% book.categories.each do |category| %>
    <%= "#{category.name}" %>
  <% end %>

  <br>

  <%= link_to 'Link',book %>
</li>

app/views/books/_form.erb
<!--bemærk form_with, finder selv ud af om den skal route til edit eller create, ved at kigge på om objektet eksisterer i databasen allerede-->

<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% book.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :release_date %><br>
    <%= form.date_field :release_date %><br>
    <% book.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :rating %><br>
    <%= form.select :rating, [1,2,3,4,5] %><br>
    <% book.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% if book.author_id.nil? %>
    <div>
      <%= form.label 'Authors' %><br>
      <%= form.select :author_id, Author.all.collect {|author| [author.full_name, author.id]}%><br>
      <% book.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <%end %>


  <div>
    <%= form.label :categories %><br>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %><br>
    <% book.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

<p><%= link_to "Tilbage til bøger", books_path %></p>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/books/edit.erb
<h1>Edit book</h1>

<%= render "form", book: @book  %>

app/views/books/index.erb
<h1>Bøger</h1>
<h3>Her finder du alle bøger i vores database</h3>
<%= link_to "Ny bog", new_book_path %>


<ul>
  <!--benchmark tester performance forkellen mellem brug af fragment caching og uden caching-->
  <%Benchmark.bm do |benchmark|%>

    <%= benchmark.report('----uncached books----') do %>
      <% Book.all.each do |book| %>
        <%= render book %>
      <%end %>
    <% end %>

    <!--her bruges der fragment caching, af books. Dette sparer SELECT*from books, samt JOINs til hver books relaterede categories.-->
    <%= benchmark.report('----cached books----') do %>
      <% @books.each do |book| %>
        <% cache book do%>
          <%= render book %>
        <% end %>
      <%end %>
    <% end %>

  <% end %>

</ul>

<%= link_to "Tilbage til forside", root_path %>

app/views/books/new.erb
<h1>New book</h1>

<%= render "form", book: @book %>

app/views/books/show.erb
<div>
  <strong><%= @book.title %></strong>
  <p><%= @book.description %></p>
  <%= @book.release_date %>
  <br>
  <%= @book.rating  %>/5 *rating
  <br>

  <strong>Forfatter:</strong>
  <br>
  <%unless @book.author.nil? %>
    <%= @book.author.full_name  %>
  <%end %>
  <br>


</div>

<p><%= link_to "Redigér", edit_book_path(@book) %></p>

<p><%= link_to "Slet bog", book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></p>

<p><%= link_to "Tilbage til bøger", books_path %></p>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/categories/_form.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @category.errors.full_messages_for(:full_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>


<% end %>

<p><%= link_to "Tilbage til kategorier", categories_path %></p>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/categories/index.erb
<h1>Kategori</h1>

<%= link_to "Ny Kategori", new_category_path %>


<ul>

  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category %>
    </li>
  <%end %>

</ul>

<%= link_to "Tilbage til forside", root_path %>

app/views/categories/new.erb
<%= render "form", model: @category %>

app/views/categories/show.erb
<div>
  <h2><%= @category.name %></h2>
  <br>
  <strong>Bøger i denne kategori:</strong>
  <br>
  <%unless @category.books.nil? %>
    <% @category.books.each do |book| %>
      <%= link_to book.title, "/books/#{book.id}"  %>
      <br>
    <%end %>
  <%end %>
  <br>


</div>

<p><%= link_to "Tilbage til forside", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.erb
<h1>About</h1>

<%= link_to "Forside", root_path %>

app/views/pages/home.erb
<h1>Forside</h1>

<%= link_to "Forfattere", authors_path %>
<%= link_to "Bøger", books_path %>
<%= link_to "Kategorier", categories_path %>
<%= link_to "About", about_path %>